# Generated by Django 3.1.7 on 2021-04-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210409_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='note',
            new_name='food_note',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='no_amount',
        ),
        migrations.RemoveField(
            model_name='step',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='step',
            name='time',
        ),
        migrations.RemoveField(
            model_name='step',
            name='type',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit_note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='grams_equivalent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='step',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='step',
            name='procedures',
            field=models.ManyToManyField(to='recipes.Procedure'),
        ),
    ]
