# Generated by Django 3.1.7 on 2021-04-09 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210409_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='step',
            name='procedures',
        ),
        migrations.AddField(
            model_name='procedure',
            name='step',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='recipes.step'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe'),
            preserve_default=False,
        ),
    ]
