# Generated by Django 3.1.7 on 2021-04-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210409_1241'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='ingredient',
            index_together={('step', 'order')},
        ),
        migrations.AlterIndexTogether(
            name='procedure',
            index_together={('step', 'order')},
        ),
        migrations.AlterIndexTogether(
            name='step',
            index_together={('recipe', 'order')},
        ),
    ]
