# Generated by Django 3.1.7 on 2021-04-13 01:36

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210409_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='', upload_to=recipes.models.recipe_image_path),
            preserve_default=False,
        ),
    ]
