# Generated by Django 3.1.7 on 2021-04-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210414_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='waiting_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
