# Generated by Django 3.1.7 on 2021-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210420_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='grams_equivalent',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount_in_g',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='waiting_time',
            field=models.IntegerField(default=0),
        )
    ]
