# Generated by Django 3.1.7 on 2021-04-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20210423_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='icon',
        ),
    ]
